project_id = "pphdcfxucfndmwulpfwv"

[functions.ai-content-generator]
verify_jwt = false

[functions.chatbot-stream]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.create-lead]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false

[functions.send-weekly-digest]
verify_jwt = false

[functions.send-trial-ending-notification]
verify_jwt = false

[functions.validate-telegram]
verify_jwt = false

[functions.send-collab-notification]
verify_jwt = false

[functions.send-team-notification]
verify_jwt = false

[functions.telegram-password-reset]
verify_jwt = false

[functions.send-friend-notification]
verify_jwt = false
